//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// このソース コードは Microsoft.VSDesigner、バージョン 4.0.30319.1 によって自動生成されました。
// 
#pragma warning disable 1591

namespace ac.pao.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SampleSoapBinding", Namespace="http://www.pao.ac:8080/axis/Sample.jws")]
    public partial class SampleService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getPrintDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBaisuuOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAddressListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMitsumoriOperationCompleted;
        
        private System.Threading.SendOrPostCallback getKoukokuOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SampleService() {
            this.Url = "http://www.pao.ac:8080/axis/Sample.jws";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getPrintDataCompletedEventHandler getPrintDataCompleted;
        
        /// <remarks/>
        public event getBaisuuCompletedEventHandler getBaisuuCompleted;
        
        /// <remarks/>
        public event getAddressListCompletedEventHandler getAddressListCompleted;
        
        /// <remarks/>
        public event getMitsumoriCompletedEventHandler getMitsumoriCompleted;
        
        /// <remarks/>
        public event getKoukokuCompletedEventHandler getKoukokuCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://www.pao.ac:8080/axis/Sample.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("getPrintDataReturn", DataType="base64Binary")]
        public byte[] getPrintData() {
            object[] results = this.Invoke("getPrintData", new object[0]);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPrintData(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPrintData", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndgetPrintData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void getPrintDataAsync() {
            this.getPrintDataAsync(null);
        }
        
        /// <remarks/>
        public void getPrintDataAsync(object userState) {
            if ((this.getPrintDataOperationCompleted == null)) {
                this.getPrintDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPrintDataOperationCompleted);
            }
            this.InvokeAsync("getPrintData", new object[0], this.getPrintDataOperationCompleted, userState);
        }
        
        private void OngetPrintDataOperationCompleted(object arg) {
            if ((this.getPrintDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPrintDataCompleted(this, new getPrintDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://www.pao.ac:8080/axis/Sample.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("getBaisuuReturn", DataType="base64Binary")]
        public byte[] getBaisuu() {
            object[] results = this.Invoke("getBaisuu", new object[0]);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetBaisuu(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getBaisuu", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndgetBaisuu(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void getBaisuuAsync() {
            this.getBaisuuAsync(null);
        }
        
        /// <remarks/>
        public void getBaisuuAsync(object userState) {
            if ((this.getBaisuuOperationCompleted == null)) {
                this.getBaisuuOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBaisuuOperationCompleted);
            }
            this.InvokeAsync("getBaisuu", new object[0], this.getBaisuuOperationCompleted, userState);
        }
        
        private void OngetBaisuuOperationCompleted(object arg) {
            if ((this.getBaisuuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBaisuuCompleted(this, new getBaisuuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://www.pao.ac:8080/axis/Sample.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("getAddressListReturn", DataType="base64Binary")]
        public byte[] getAddressList() {
            object[] results = this.Invoke("getAddressList", new object[0]);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAddressList(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAddressList", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndgetAddressList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void getAddressListAsync() {
            this.getAddressListAsync(null);
        }
        
        /// <remarks/>
        public void getAddressListAsync(object userState) {
            if ((this.getAddressListOperationCompleted == null)) {
                this.getAddressListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAddressListOperationCompleted);
            }
            this.InvokeAsync("getAddressList", new object[0], this.getAddressListOperationCompleted, userState);
        }
        
        private void OngetAddressListOperationCompleted(object arg) {
            if ((this.getAddressListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAddressListCompleted(this, new getAddressListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://www.pao.ac:8080/axis/Sample.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("getMitsumoriReturn", DataType="base64Binary")]
        public byte[] getMitsumori() {
            object[] results = this.Invoke("getMitsumori", new object[0]);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetMitsumori(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getMitsumori", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndgetMitsumori(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void getMitsumoriAsync() {
            this.getMitsumoriAsync(null);
        }
        
        /// <remarks/>
        public void getMitsumoriAsync(object userState) {
            if ((this.getMitsumoriOperationCompleted == null)) {
                this.getMitsumoriOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMitsumoriOperationCompleted);
            }
            this.InvokeAsync("getMitsumori", new object[0], this.getMitsumoriOperationCompleted, userState);
        }
        
        private void OngetMitsumoriOperationCompleted(object arg) {
            if ((this.getMitsumoriCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMitsumoriCompleted(this, new getMitsumoriCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://www.pao.ac:8080/axis/Sample.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("getKoukokuReturn", DataType="base64Binary")]
        public byte[] getKoukoku() {
            object[] results = this.Invoke("getKoukoku", new object[0]);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetKoukoku(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getKoukoku", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndgetKoukoku(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void getKoukokuAsync() {
            this.getKoukokuAsync(null);
        }
        
        /// <remarks/>
        public void getKoukokuAsync(object userState) {
            if ((this.getKoukokuOperationCompleted == null)) {
                this.getKoukokuOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetKoukokuOperationCompleted);
            }
            this.InvokeAsync("getKoukoku", new object[0], this.getKoukokuOperationCompleted, userState);
        }
        
        private void OngetKoukokuOperationCompleted(object arg) {
            if ((this.getKoukokuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getKoukokuCompleted(this, new getKoukokuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getPrintDataCompletedEventHandler(object sender, getPrintDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPrintDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPrintDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getBaisuuCompletedEventHandler(object sender, getBaisuuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBaisuuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBaisuuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getAddressListCompletedEventHandler(object sender, getAddressListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAddressListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAddressListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getMitsumoriCompletedEventHandler(object sender, getMitsumoriCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMitsumoriCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMitsumoriCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getKoukokuCompletedEventHandler(object sender, getKoukokuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getKoukokuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getKoukokuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591